pytest:
  image: python:3.6
  variables:
    QT_QPA_PLATFORM: "offscreen"
  script:
    - apt-get update -q -y
    - apt-get -q -y --no-install-recommends install python3-pyqt5
    - apt-get -q -y --no-install-recommends install python3-venv
    - python3 -m venv pytestvenv
    - source pytestvenv/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pytest --cov=Lupr -vv -s --durations=10 tests/
